[package]
name = "fastcord-app"
description = "fastcord desktop application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "fastcord"
path = "src/main.rs"

[dependencies]
fastcord-model.workspace = true
fastcord-discord.workspace = true
fastcord-platform.workspace = true
fastcord-media.workspace = true
fastcord-audio.workspace = true
iced.workspace = true
iced_renderer.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
zeroize.workspace = true
futures-util.workspace = true
reqwest.workspace = true
image.workspace = true
filetime.workspace = true
sha2.workspace = true
rfd.workspace = true
parking_lot.workspace = true
bytes.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
